---
- name: Copy configuration
  copy:
    src: "{{ item.src_filename }}"
    dest: "{{ ansible_user_dir }}/.ssh/{{ item.dest_filename }}"
  with_items:
    - src_filename: "github.pub.gpg"
      dest_filename: "github.pub"
    - src_filename: "github.gpg"
      dest_filename: "github"

- name: Ensure the github private key has proper permissions
  file:
    path:  "{{ ansible_user_dir }}/.ssh/github"
    mode: 0400
