---

- name: Install deps
  apt:
    name: bzip2
    state: present
  become: yes
  become_method: sudo
    
- name: Copy configuration
  copy:
    src: pythonrc
    dest: "{{ ansible_user_dir }}/.pythonrc"

- name: Copy PyPi configuration
  copy:
    src: pypirc
    dest: "{{ ansible_user_dir }}/.pypirc"

- name: Ensure PyPi configuration has proper permissions
  file:
    path:  "{{ ansible_user_dir }}/.pypirc"
    mode: 0400

- name: Check if Anaconda is installed
  stat:
    path: '{{ anaconda_source_script_path }}'
  register: anaconda_source_script

- name: Install Anaconda
  when: not anaconda_source_script.stat.exists
  block:
    - name: Download Anaconda installer
      when: not anaconda_source_script.stat.exists
      get_url:
        url: '{{ anaconda_installer_url}}'
        dest: '{{ anaconda_installer_dest }}'
        timeout: '{{ anaconda_download_timeout_sec }}'
        checksum: '{{ anaconda_installer_checksum }}'
        mode: '0755'

    - name: Install Anaconda
      command: '{{ anaconda_installer_dest }} -b -p {{ anaconda_home_dir }}'
      args:
        creates: '{{ anaconda_home_dir }}'

    - name: Remove installer
      file:
        path: '{{ anaconda_installer_dest }}'
        state: 'absent'  

- name: Install virtualenvwrapper
  pip:
    name: virtualenvwrapper
    executable: '{{ anaconda_home_dir }}/bin/pip'


- name: Add zsh configuration
  synchronize:
    src: "zsh-custom/"
    dest: "{{ ansible_user_dir }}/.zsh-custom/"
    recursive: true

