---

- name: Install deps
  apt:
    name: bzip2
    state: latest
  become: yes
  become_method: sudo

- name: Copy configuration
  copy:
    src: pythonrc
    dest: "{{ ansible_user_dir }}/.pythonrc"

- name: Check if Miniconda is installed
  stat:
    path: '{{ miniconda_source_script_path }}'
  register: miniconda_source_script

- name: Install Miniconda
  when: not miniconda_source_script.stat.exists
  block:
    - name: Download Miniconda installer
      when: not miniconda_source_script.stat.exists
      get_url:
        url: '{{ miniconda_installer_url}}'
        dest: '{{ miniconda_installer_dest }}'
        timeout: '{{ miniconda_download_timeout_sec }}'
        mode: '0755'

    - name: Install Miniconda
      command: '{{ miniconda_installer_dest }} -b -p {{ miniconda_home_dir }}'
      args:
        creates: '{{ miniconda_home_dir }}'

    - name: Remove installer
      file:
        path: '{{ miniconda_installer_dest }}'
        state: 'absent'

- name: Install virtualenvwrapper
  pip:
    name: virtualenvwrapper
    executable: '{{ miniconda_home_dir }}/bin/pip'


- name: Add zsh configuration
  template:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.zsh-custom/env/{{ item | basename }}"
  with_fileglob:
    - ./*.zsh-env
