---
- name: link configuration
  file:
    src: "{{ confz_files }}/{{ role_name }}/config.confz"
    dest: "{{ ansible_user_dir }}/.ssh/config"
    state: link
    force: yes

- name: link environment configuration
  file:
    src: "{{ confz_files }}/{{ role_name }}/ssh.zsh-env"
    dest: "{{ ansible_user_dir }}/.zsh-custom/env/ssh.zsh-env"
    state: link
    force: yes
