---
- name: install git
  apt:
    name: git
    state: latest
  become: yes
  become_method: sudo

- name: link git configuration
  file:
    src: "{{ confz_files }}/{{ role_name }}/gitconfig"
    dest: "{{ ansible_user_dir }}/.gitconfig"
    state: link
    force: yes

- name: link environment configuration
  file:
    src: "{{ confz_files }}/{{ role_name }}/git.zsh-env"
    dest: "{{ ansible_user_dir }}/.zsh-custom/env/git.zsh-env"
    state: link
    force: yes
