---
- name: install
  apt:
    name: emacs
    state: latest
  become: yes
  become_method: sudo

- name: link configuration
  file:
    src: "{{ confz_files }}/{{ role_name }}/emacs.d"
    dest: "{{ ansible_user_dir }}/.emacs.d"
    state: link
    force: yes

- name: link environment configuration
  file:
    src: "{{ confz_files }}/{{ role_name }}/emacs.zsh-env"
    dest: "{{ ansible_user_dir }}/.zsh-custom/env/emacs.zsh-env"
    state: link
    force: yes
