---
- name: install dependencies
  apt:
    name:
      - ruby-full
      - build-essential
    state: latest
  become: yes
  become_method: sudo

- name: link environment configuration
  file:
    src: "{{ confz_files }}/{{ role_name }}/jekyll.zsh-env"
    dest: "{{ ansible_user_dir }}/.zsh-custom/env/jekyll.zsh-env"
    state: link
    force: yes

- name: install
  gem:
    name: "{{ item }}"
    state: latest
    user_install: no
    install_dir: "{{ ansible_user_dir }}/opt/gems"
  with_items:
    - bundler
    - jekyll
