---
- name: install git
  apt:
    name: git
    state: latest
  become: yes
  become_method: sudo

- name: clone confz-files
  git:
    repo: git@github.com:m09/confz-files.git
    dest: "{{ confz_files }}"
    force: yes

- name: link git configuration
  file:
    src: "{{ confz_files }}/{{ role_name }}/gitconfig"
    dest: "{{ ansible_user_dir }}/.gitconfig"
    state: link
    force: yes
