---
- name: install
  apt:
    name:
      - texlive
      - texlive-lang-english
      - texlive-lang-french
      - texlive-xetex
    state: latest
  become: yes
  become_method: sudo

- name: link configuration
  file:
    src: "{{ confz_files }}/{{ role_name }}/latexmkrc"
    dest: "{{ ansible_user_dir }}/.latexmkrc"
    state: link
    force: yes
