---
- name: install
  apt:
    name:
      - latexmk
      - texlive
      - texlive-lang-english
      - texlive-lang-french
      - texlive-science
      - texlive-xetex
    state: latest
  become: yes
  become_method: sudo

- name: link configuration
  file:
    src: "{{ confz_files }}/{{ role_name }}/{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    state: link
    force: yes
  with_items:
    - latexmkrc
    - indentconfig.yml
